import json
import re
from fastapi import FastAPI, HTTPException, BackgroundTasks
from pydantic import BaseModel
from core.models import MODEL_REGISTRY, send_request
from core.router import AutopilotRouter
# Import Phase 5 analytics functions
from core.analytics import log_completion_metrics, log_audit_metrics

app = FastAPI(
    title="LLM Cost Autopilot API",
    description="Intelligent routing gateway with background evaluation, recovery loops, and analytics telemetry.",
    version="1.3.0"
)
router_engine = AutopilotRouter()

class PromptRequest(BaseModel):
    prompt: str

# --- Phase 4 & 5 Combined: Background Evaluator, Recovery & Logging Loop ---
def verify_and_recover_response(prompt: str, cheap_model_response: str):
    print(f"\n[BACKGROUND EVALUATOR] Auditing cheap response for quality verification...")
    
    judge_config = MODEL_REGISTRY.get("qwen-large")
    judge_prompt = f"""
You are an expert AI Quality Auditor. Your job is to grade the quality of a lightweight AI model's response compared to the original user intent.

[USER PROMPT]:
{prompt}

[LIGHTWEIGHT MODEL RESPONSE]:
{cheap_model_response}

Is the lightweight model's response accurate, safe, and helpful? Grade it strictly from 1 to 5 (where 5 is perfect and 1 is completely broken or unhelpful). 
Respond ONLY with a single raw JSON block containing your numerical 'score' and a one-sentence 'reason'. Do not wrap it in markdown text or use math formatting backslashes.
Example format: {{"score": 4, "reason": "The answer is accurate but missing slight context."}}
"""
    try:
        judge_receipt = send_request(judge_prompt, judge_config, tier="verification_judge")
        raw_output = judge_receipt.text.strip()
        
        print(f"--- [AUDIT REPORT COMPLETED] ---")
        
        clean_json_str = re.sub(r"```json\s*|\s*```", "", raw_output).strip()
        clean_json_str = clean_json_str.replace("\\(", "(").replace("\\)", ")")
        
        audit_data = json.loads(clean_json_str)
        score = int(audit_data.get("score", 5))
        reason = audit_data.get("reason", "")
        
        print(f"Parsed Score: {score}/5 | Reason: {reason}")
        
        was_recovered = False
        if score <= 3:
            print(f"\n🚨 [CRITICAL ALERT] Quality threshold breached (Score: {score})!")
            print(f"🔄 [PHASE 4 RECOVERY ACTIVATED] Escalating task to heavy-duty model...")
            send_request(prompt, judge_config, tier="tier_3_fallback")
            print(f"✅ [RECOVERY COMPLETE] Clean response generated by 7B Master Model.")
            was_recovered = True
        else:
            print(f"🛡️ [QUALITY SECURE] Tier 1 response passed the quality threshold.")
            
        # --- PHASE 5: Log Quality Telemetry ---
        log_audit_metrics(score, reason, was_recovered)
        print(f"📈 [METRICS RECORDED] Quality audit metrics appended to log storage.")
        print(f"--------------------------------")

    except Exception as e:
        print(f"[BACKGROUND ENGINE ERROR] Verification/Recovery metrics failed: {str(e)}")


# --- Main HTTP Completions Route ---
@app.post("/v1/completions")
async def handle_completion(payload: PromptRequest, background_tasks: BackgroundTasks):
    if not payload.prompt.strip():
        raise HTTPException(status_code=400, detail="Invalid request: Prompt content cannot be empty.")
    
    try:
        tier, designated_model_key = router_engine.route_request(payload.prompt)
        model_config = MODEL_REGISTRY.get(designated_model_key)
        
        execution_receipt = send_request(payload.prompt, model_config, tier)
        
        # --- PHASE 5: Log Live Core Completion Metrics ---
        # Convert our pydantic response token format into a dictionary for the logger
        log_completion_metrics(execution_receipt.model_dump())
        
        if tier == "tier_1":
            background_tasks.add_task(verify_and_recover_response, payload.prompt, execution_receipt.text)
        
        return execution_receipt

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
async def health_check():
    return {"status": "healthy", "engine": "LLM Cost Autopilot Core"}